# Generated by Django 5.2 on 2025-04-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='score',
            field=models.CharField(default='0', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidade',
            field=models.CharField(choices=[('VMD', 'Vila Madalena'), ('BEL', 'Bela Vista'), ('PAR', 'Paraiso'), ('VMR', 'Vila Mariana'), ('FRE', 'Frei Caneca'), ('PIN', 'Pinheiros'), ('ITU', 'Alameda Itu'), ('CAP', 'Capote Valente'), ('MEL', 'Melo Alves')], default='BEL', max_length=3, null=True),
        ),
    ]
