# Generated by Django 5.2 on 2025-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_cliente_score_cliente_unidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='interesses',
            new_name='observacoes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apto',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='cliente',
            name='imgcnh',
            field=models.ImageField(default='', null=True, upload_to=None),
        ),
    ]
