# Generated by Django 5.2 on 2025-04-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_cliente_imgcnh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imgcnh',
        ),
    ]
