# Generated by Django 5.2 on 2025-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_cliente_imgcnh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens/'),
        ),
    ]
