# Generated by Django 5.2 on 2025-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_cliente_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documentacaoenviada',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='visitarealizada',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(default=None, null=True, upload_to='imagens/'),
        ),
    ]
