# Generated by Django 5.2 on 2025-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_cliente_documentacaoenviada_cliente_visitarealizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpjunidade',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpfresidente',
            field=models.CharField(default='', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecounidade',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estcivil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a) judicialmente', 'Separado(a) judicialmente')], default='Solteiro(a)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iniciocontrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='matriculaunidade',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomeresidente',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nomeunidade',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nriptuunidade',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='prazocontrato',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rgresidente',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rgrne',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='terminocontrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vagaunidade',
            field=models.CharField(choices=[('0', 'Nenhuma'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
