# Generated by Django 5.2 on 2025-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_cliente_cnpjunidade_cliente_cpfresidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prazocontrato',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
