# Generated by Django 5.2 on 2025-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_cliente_prazocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prazocontrato',
            field=models.IntegerField(null=True),
        ),
    ]
