# Generated by Django 5.2 on 2025-05-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_cliente_vrunidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominionome', models.CharField(blank=True, max_length=100, verbose_name='Condominio')),
                ('condominiocnpj', models.CharField(default='', max_length=14, null=True, verbose_name='CNPJ')),
                ('condominiomatricula', models.CharField(default='', max_length=30, null=True, verbose_name='Número da matrícula')),
                ('condominioendereco', models.CharField(default='', max_length=120, null=True, verbose_name='Endereço')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apto',
            field=models.CharField(default=0, max_length=4, verbose_name='Apto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpjunidade',
            field=models.CharField(default='', max_length=14, null=True, verbose_name='CNPJ condomínio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpfresidente',
            field=models.CharField(default='', max_length=14, null=True, verbose_name='CPF do residente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documentacaoenviada',
            field=models.FileField(default=None, null=True, upload_to='', verbose_name='Pré-Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enderecounidade',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Endereço da unidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estcivil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a) judicialmente', 'Separado(a) judicialmente')], default='Solteiro(a)', max_length=30, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(default=None, null=True, upload_to='imagens/', verbose_name='Imagem CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='iniciocontrato',
            field=models.DateField(blank=True, null=True, verbose_name='Início do contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matriculaunidade',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Número da matrícula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeresidente',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nome do residente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeunidade',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nome do condomínio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nriptuunidade',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Número IPTU'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prazocontrato',
            field=models.IntegerField(default=0, null=True, verbose_name='Prazo do Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='', max_length=40, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rgresidente',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='RG do residente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rgrne',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='RG/RNE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='score',
            field=models.CharField(default='0', max_length=5, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='terminocontrato',
            field=models.DateField(blank=True, null=True, verbose_name='Término do contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='unidade',
            field=models.CharField(choices=[('VMD', 'Vila Madalena'), ('BEL', 'Bela Vista'), ('PAR', 'Paraiso'), ('VMR', 'Vila Mariana'), ('FRE', 'Frei Caneca'), ('PIN', 'Pinheiros'), ('ITU', 'Alameda Itu'), ('CAP', 'Capote Valente'), ('MEL', 'Melo Alves')], default='BEL', max_length=3, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vagaunidade',
            field=models.CharField(choices=[('0', 'Nenhuma'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1, null=True, verbose_name='Vaga(s)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='visitarealizada',
            field=models.BooleanField(default=False, null=True, verbose_name='Visita realizado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vrunidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamentonro', models.CharField(blank=True, null=True, verbose_name='Apto')),
                ('apartamentovagas', models.CharField(choices=[('0', 'Nenhuma'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1, null=True, verbose_name='Vaga(s)')),
                ('apartamentoiptu', models.CharField(default='', max_length=20, null=True, verbose_name='Número IPTU')),
                ('apartamentovrunidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('Condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.condominio')),
            ],
        ),
    ]
