# Generated by Django 5.2 on 2025-05-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_condominio_alter_cliente_apto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.apartamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.condominio'),
        ),
    ]
