# Generated by Django 5.2 on 2025-05-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_consultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.consultor'),
        ),
    ]
