# Generated by Django 5.2 on 2025-05-07 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_cliente_consultor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preclienteNome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preclienteCpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('precoclienteEmail', models.EmailField(help_text='Exemplo: usuario@provedor.com', max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail')),
                ('preclienteJson', models.TextField(blank=True, null=True, verbose_name='Json')),
                ('preclienteDataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
        ),
    ]
