# Generated by Django 5.2 on 2025-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_precliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='preclienteApontamentos',
            field=models.CharField(blank=True, null=True, verbose_name='Apontamentos'),
        ),
        migrations.AddField(
            model_name='precliente',
            name='preclienteAvalAuto',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Avaliação Automática'),
        ),
        migrations.AddField(
            model_name='precliente',
            name='preclienteAvaliacao',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='precliente',
            name='preclienteRendaPresumida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='precliente',
            name='preclienteScore',
            field=models.CharField(blank=True, default='0', null=True, verbose_name='Score'),
        ),
    ]
