# Generated by Django 5.2 on 2025-05-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_precliente_preclienteapontamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='condominionomecomercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Comercial do Condominio'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='condominionomepropriedade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Propriedade'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominiomatricula',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='IPTU'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominionome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Condominio'),
        ),
        migrations.AlterField(
            model_name='precliente',
            name='preclienteRendaPresumida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Presumida'),
        ),
    ]
