# Generated by Django 5.2 on 2025-05-09 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_condominio_condominionomecomercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='PreCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.precliente'),
        ),
    ]
