# Generated by Django 5.2 on 2025-05-09 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_cliente_precliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='PreCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.precliente', unique=True),
        ),
    ]
