# Generated by Django 5.2 on 2025-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_alter_cliente_precliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='preclienteRendaFamiliar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Familiar'),
        ),
    ]
