# Generated by Django 5.2 on 2025-05-13 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_precliente_preclienterendafamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celularresidente',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular residente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='emailresidente',
            field=models.EmailField(blank=True, help_text='Exemplo: usuario@provedor.com', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail do residente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='enderecoresidente',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Endereço do residente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estadocivilresidente',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a) judicialmente', 'Separado(a) judicialmente')], default='Solteiro(a)', max_length=30, null=True, verbose_name='Estado civil do residente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissaoresidente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Profissão do residente'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominiocnpj',
            field=models.CharField(default='', max_length=17, null=True, verbose_name='CNPJ'),
        ),
    ]
