# Generated by Django 5.2 on 2025-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_cliente_celularresidente_cliente_emailresidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpjunidade',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CNPJ condomínio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enderecounidade',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Endereço da unidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matriculaunidade',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Número da matrícula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeunidade',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nome do condomínio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nriptuunidade',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Número IPTU'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vagaunidade',
            field=models.CharField(blank=True, choices=[('0', 'Nenhuma'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1, null=True, verbose_name='Vaga(s)'),
        ),
    ]
