# Generated by Django 5.2 on 2025-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_alter_cliente_cnpjunidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpfresidente',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='CPF do residente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomeresidente',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nome do residente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='prazocontrato',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Prazo do Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rgresidente',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='RG do residente'),
        ),
    ]
