# Generated by Django 5.2 on 2025-05-13 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0028_alter_cliente_cpfresidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precliente',
            name='preclienteNome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='precliente',
            name='precoclienteEmail',
            field=models.EmailField(blank=True, help_text='Exemplo: usuario@provedor.com', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail'),
        ),
    ]
