# Generated by Django 5.2 on 2025-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0029_alter_precliente_preclientenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='score',
            field=models.CharField(blank=True, default='0', max_length=5, null=True, verbose_name='Score'),
        ),
    ]
