# Generated by Django 5.2 on 2025-05-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0030_alter_cliente_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datainiciodesconto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início do desconto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dataterminodesconto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término do desconto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='percentualdesconto',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True, verbose_name='Percentual de desconto'),
        ),
    ]
