# Generated by Django 5.2 on 2025-05-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0032_alter_cliente_percentualdesconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='percentualdesconto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Percentual de desconto'),
        ),
    ]
