# Generated by Django 5.2 on 2025-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0033_alter_cliente_percentualdesconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='preclienteDataVisita',
            field=models.DateField(blank=True, null=True, verbose_name='Data da visita'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominiocnpj',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='CNPJ'),
        ),
    ]
