# Generated by Django 5.2 on 2025-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0034_precliente_preclientedatavisita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='isencaomulta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Isenção de contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imagens/', verbose_name='Imagem CNH'),
        ),
    ]
