# Generated by Django 5.2 on 2025-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0035_cliente_isencaomulta_alter_cliente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='isencaomulta',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', null=True, verbose_name='Isenção de contrato'),
        ),
    ]
