# Generated by Django 5.2 on 2025-05-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0036_alter_cliente_isencaomulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='isencaomulta',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Isenção de contrato'),
        ),
    ]
