# Generated by Django 5.2 on 2025-05-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0037_alter_cliente_isencaomulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='preclienteCondominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.condominio'),
        ),
    ]
