# Generated by Django 5.2 on 2025-05-23 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0038_precliente_preclientecondominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='processoassinaturaid',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID do processo de assinatura'),
        ),
        migrations.AlterField(
            model_name='precliente',
            name='preclienteCondominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.condominio', verbose_name='Condominio'),
        ),
    ]
