# Generated by Django 5.2 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0039_cliente_processoassinaturaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enderecowebhook',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Endereço Webhook'),
        ),
    ]
