# Generated by Django 5.2 on 2025-05-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0040_cliente_enderecowebhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificacaoTitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título')),
                ('NotificacaoDescricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('NotificacaoData', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('NotificacaoTipo', models.CharField(blank=True, choices=[('A', 'Alerta'), ('I', 'Informação'), ('E', 'Erro')], max_length=1, null=True, verbose_name='Tipo')),
                ('NotificacaoLido', models.BooleanField(blank=True, default=False, null=True, verbose_name='Lido')),
                ('Consultor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.consultor')),
            ],
        ),
    ]
