# Generated by Django 5.2 on 2025-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0041_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datahoraassinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da assinatura'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documentacaoassinada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documentação assinada'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Celular'),
        ),
    ]
