# Generated by Django 5.2 on 2025-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0042_cliente_datahoraassinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='statusassinatura',
            field=models.CharField(blank=True, default='Pendente', max_length=20, null=True, verbose_name='Status da assinatura'),
        ),
    ]
