# Generated by Django 5.2 on 2025-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0043_cliente_statusassinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='statusassinatura',
            field=models.CharField(blank=True, default='Pendente', max_length=30, null=True, verbose_name='Status da assinatura'),
        ),
    ]
