# Generated by Django 5.2 on 2025-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0044_alter_cliente_statusassinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='NotificacaoDescricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
    ]
