# Generated by Django 5.2 on 2025-05-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0045_alter_notificacao_notificacaodescricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='precliente',
            name='Consultor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.consultor', verbose_name='Consultor'),
        ),
    ]
