# Generated by Django 5.2 on 2025-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0046_precliente_consultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Celular'),
        ),
    ]
