# Generated by Django 5.2 on 2025-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0047_alter_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logacessoUsuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário')),
                ('logacessoData', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('logacessoDataHora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
            ],
        ),
    ]
