# Generated by Django 5.2 on 2025-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0048_logacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='processofinalizado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Processo finalizado'),
        ),
    ]
