# Generated by Django 5.2 on 2025-06-12 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0049_cliente_processofinalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precliente',
            name='precoclienteEmail',
            field=models.EmailField(blank=True, help_text='Exemplo: usuario@provedor.com', max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Digite um e-mail válido')], verbose_name='E-mail'),
        ),
    ]
